### ISSUE TITLE
Cannot do initial syncdb when dockit is in INSTALLED_APPS

### ISSUE THREAD

**Issue by kmooney** [zbyte64/django-dockit#10]
When dockit is in INSTALLED_APPS, I cannot do an initial syncdb.  I don't have the original stack trace, but found that it was almost identical to the one referenced here:  

http://stackoverflow.com/questions/2125326/django-cant-syncdb-after-drop-create-database

**Comment by kmooney** [comment]
To clarify, that's about what I saw when I tried to do the initial sync on heroku.  Running locally, I got this: 

ERROR:  relation "django_content_type" does not exist at character 136
STATEMENT:  SELECT "django_content_type"."id", "django_content_type"."name", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'dockitpermission'  AND "django_content_type"."app_label" = 'dockit' )
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_manager(settings)
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/core/management/base.py", line 219, in execute
    self.validate()
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/core/management/base.py", line 249, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/core/management/validation.py", line 36, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/db/models/loading.py", line 146, in get_app_errors
    self._populate()
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name)
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in load_app
    models = import_module('.models', app_name)
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/dbtemplates/models.py", line 10, in <module>
    from dbtemplates.conf import settings
  File "/Users/Kevin/.virtualenv/dev42/lib/python2.7/site-packages/dbtemplates/conf.py", line 6, in <module>
    from appconf import AppConf
ImportError: No module named appconf

**Comment by zbyte64** [comment]
Your local site has dbtemplates installed which requires django-appconf which dbtemplates fails to include in it's requirements.

**Comment by zbyte64** [comment]
There are some possible issues with loading up the indexes before the tables are created which could cause similar results to what you are seeing. The apploading branch aims to clean up the code surrounding the registering of documents and indexes and will specifically hold back on firing certain signals until the app is ready.

**Comment by zbyte64** [comment]
Please pull down the latest code and see if this issue still persists. Just did allot of refactoring and added some checks to keep the djangodocument backend from creating indexes before the index tables are created.

**Comment by kmooney** [comment]
Looks good.  I was able to syncdb on a test install this morning using the latest master.
