### ISSUE TITLE
Test failure on Python 2.5

### ISSUE THREAD

**Issue by msabramo** [zbyte64/django-dockit#5]
```
marc@hyperion:~/dev/git-repos/django-dockit
09:09:03 $ .tox/py25/bin/python setup.py test --quiet
running test
running egg_info
writing django_dockit.egg-info/PKG-INFO
writing top-level names to django_dockit.egg-info/top_level.txt
writing dependency_links to django_dockit.egg-info/dependency_links.txt
reading manifest file 'django_dockit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'django_dockit.egg-info/SOURCES.txt'
running build_ext
Creating test database for alias 'default'...
.............................................................EE.E..............................................................................Destroying test database for alias 'default'...

======================================================================
ERROR: test_data_init (dockit.tests.forms.form.FormTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marc/dev/git-repos/django-dockit/dockit/tests/forms/form.py", line 35, in test_data_init
    self.assertTrue(form.is_valid())
  File "/Users/marc/dev/git-repos/django-dockit/Django-1.3.1-py2.5.egg/django/forms/forms.py", line 121, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/Users/marc/dev/git-repos/django-dockit/Django-1.3.1-py2.5.egg/django/forms/forms.py", line 112, in _get_errors
    self.full_clean()
  File "/Users/marc/dev/git-repos/django-dockit/Django-1.3.1-py2.5.egg/django/forms/forms.py", line 267, in full_clean
    self._clean_fields()
  File "/Users/marc/dev/git-repos/django-dockit/dockit/forms/forms.py", line 257, in _clean_fields
    if len(arg_spec.args) > 2:
AttributeError: 'tuple' object has no attribute 'args'

======================================================================
ERROR: test_instance_create (dockit.tests.forms.form.FormTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marc/dev/git-repos/django-dockit/dockit/tests/forms/form.py", line 53, in test_instance_create
    self.assertTrue(form.is_valid())
  File "/Users/marc/dev/git-repos/django-dockit/Django-1.3.1-py2.5.egg/django/forms/forms.py", line 121, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/Users/marc/dev/git-repos/django-dockit/Django-1.3.1-py2.5.egg/django/forms/forms.py", line 112, in _get_errors
    self.full_clean()
  File "/Users/marc/dev/git-repos/django-dockit/Django-1.3.1-py2.5.egg/django/forms/forms.py", line 267, in full_clean
    self._clean_fields()
  File "/Users/marc/dev/git-repos/django-dockit/dockit/forms/forms.py", line 257, in _clean_fields
    if len(arg_spec.args) > 2:
AttributeError: 'tuple' object has no attribute 'args'

======================================================================
ERROR: test_instance_update (dockit.tests.forms.form.FormTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marc/dev/git-repos/django-dockit/dockit/tests/forms/form.py", line 46, in test_instance_update
    self.assertTrue(form.is_valid())
  File "/Users/marc/dev/git-repos/django-dockit/Django-1.3.1-py2.5.egg/django/forms/forms.py", line 121, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/Users/marc/dev/git-repos/django-dockit/Django-1.3.1-py2.5.egg/django/forms/forms.py", line 112, in _get_errors
    self.full_clean()
  File "/Users/marc/dev/git-repos/django-dockit/Django-1.3.1-py2.5.egg/django/forms/forms.py", line 267, in full_clean
    self._clean_fields()
  File "/Users/marc/dev/git-repos/django-dockit/dockit/forms/forms.py", line 257, in _clean_fields
    if len(arg_spec.args) > 2:
AttributeError: 'tuple' object has no attribute 'args'

----------------------------------------------------------------------
Ran 143 tests in 0.282s

FAILED (errors=3)
```

**Comment by zbyte64** [comment]
Added python 2.5 to travis and the issue should have been fixed with: cba437b
